fun main() {
    val calculo = Calculos()
    println("Calculos De Fisica")
    println("Digite o que quer calcular:")
    println("1-Força peso, 2-Força Centripeta, 3-Impulso, 4-Força Elastica, 5-Velocidade Media 6-MRU 7-MRUV")
    val escolha: Int = readLine()!!.toInt()
    if (escolha == 1) {
        println("Digite o valor da massa:")
        val massa: Float = readLine()!!.toFloat()
        println("Digite o valor da gravidade:")
        val gravidade: Float = readLine()!!.toFloat()
        val forcaPeso = calculo.forcaPeso(massa, gravidade)
        print("O resultado da Força Peso é $forcaPeso")
    } else if (escolha == 2) {
        println("Digite o valor da massa:")
        val massa: Float = readLine()!!.toFloat()
        println("Digite o valor do raio:")
        val raio: Float = readLine()!!.toFloat()
        println("Digite o valor da velocidade:")
        val velocidade: Float = readLine()!!.toFloat()
        val forcaCentripeta = calculo.forcaCentripeta(massa, raio, velocidade)
        println("O valor da força centripeta é $forcaCentripeta")
    } else if (escolha == 3) {
        println("Digite o valor da força:")
        val forca: Double = readLine()!!.toDouble()
        println("Digite o valor da massa:")
        val massa: Double = readLine()!!.toDouble()
        println("Digite o valor da Velocidade Inicial:")
        val vlci: Double = readLine()!!.toDouble()
        println("Digite o valor da Velocidade Final:")
        val vlcf: Double = readLine()!!.toDouble()
        val impulso = calculo.impulso(forca, massa, vlci, vlcf)
        println("O valor do impulso é $impulso")
    } else if (escolha == 4) {
        println("Digite o valor da constante:")
        val constante: Float = readLine()!!.toFloat()
        println("Digite o valor da deformação:")
        val deformacao: Float = readLine()!!.toFloat()
        val forcaElastica = calculo.forcaElastica(constante, deformacao)
        println("O valor da Força Elastica é $forcaElastica")
    } else if (escolha == 5) {
        println("Digite o valor da distancia:")
        val distancia: Double = readLine()!!.toDouble()
        println("Digite o valor do tempo:")
        val tempo: Double = readLine()!!.toDouble()
        val velocidadeMedia = calculo.velocidadeMedia(distancia, tempo)
        println("A velocidade média é $velocidadeMedia")
    } else if (escolha == 6) {
        println("Digite o valor da distancia inicial:")
        val dsti: Double = readLine()!!.toDouble()
        println("Digite o valor da distancia final:")
        val dstf: Double = readLine()!!.toDouble()
        println("Digite o valor do tempo inicial:")
        val tmpi: Double = readLine()!!.toDouble()
        println("Digite o valor do tempo final:")
        val tmpf: Double = readLine()!!.toDouble()
        val mru = calculo.mru(dsti, dstf, tmpi, tmpf)
        println("O valor do MRU é $mru")
    } else if (escolha == 7) {
        println("Digite o valor da velocidade inicial:")
        val vldi: Double = readLine()!!.toDouble()
        println("Digite o valor da aceleração:")
        val aceleracao: Double = readLine()!!.toDouble()
        println("Digite o valor da instante:")
        val instante: Double = readLine()!!.toDouble()
        val mruv = calculo.mruv(vldi, aceleracao, instante)
        println("O valor da MRUV é $mruv")
    } else {
        println("Digite um numero de conta valido...")
    }
}